colors.draw_bold_text_with_bright_colors = false
#custom_cursor_colors = true
general.live_config_reload = true

[window]
dynamic_padding = true
decorations = "None"
startup_mode = "Maximized"
opacity = 0.95
blur = true

[window.dimensions]
columns = 100
lines = 85

[window.padding]
x = 10
y = 5

[scrolling]
history = 0
multiplier = 3

[font]
size = 13
# use_thin_strokes = true

[font.normal]
family = "RecMonoLinear Nerd Font Mono"
style = "Regular"

[font.bold]
family = "RecMonoLinear Nerd Font Mono"
style = "Bold"

[font.italic]
family = "RecMonoLinear Nerd Font Mono"
style = "Regular Italic"

[font.offset]
x = 0
y = 3

[font.glyph_offset]
x = 0
y = 0

[colors.primary]
background = '#1c2023'
foreground = '#c7ccd1'

[colors.cursor]
text = '#1c2023'
cursor = '#c7ccd1'

[colors.normal]
black   = '#1c2023'
red     = '#c7ae95'
green   = '#95c7ae'
yellow  = '#aec795'
blue    = '#ae95c7'
magenta = '#c795ae'
cyan    = '#95aec7'
white   = '#c7ccd1'

[colors.bright]
black   = '#747c84'
red     = '#c7ae95'
green   = '#95c7ae'
yellow  = '#aec795'
blue    = '#ae95c7'
magenta = '#c795ae'
cyan    = '#95aec7'
white   = '#f3f4f5'

[bell]
animation = "EaseOutExpo"
color = "0xffffff"
duration = 0

[mouse]
hide_when_typing = false

[cursor]
style = "Block"
unfocused_hollow = true

[keyboard]
bindings = [
  { key = "A", mods = "Command", chars = "\u0001" },
  { key = "C", mods = "Command", chars = "\u0003" },
  { key = "D", mods = "Command", chars = "\u0004" },
  { key = "E", mods = "Command", chars = "\u0005" },
  { key = "H", mods = "Command", chars = "\u0008" },
  { key = "I", mods = "Command", chars = "\u0009" },
  { key = "J", mods = "Command", chars = "\u000a" },
  { key = "K", mods = "Command", chars = "\u000b" },
  { key = "L", mods = "Command", chars = "\u000c" },
  { key = "O", mods = "Command", chars = "\u000f" },
  { key = "R", mods = "Command", chars = "\u0012" },
  { key = "T", mods = "Command", chars = "\u0014" },
  { key = "U", mods = "Command", chars = "\u0015" },
  { key = "W", mods = "Command", chars = "\u0017" },
  { key = "X", mods = "Command", chars = "\u0018" },
  { key = "Y", mods = "Command", chars = "\u0019" },
  { key = "Z", mods = "Command", chars = "\u001a" },
]
