colors.draw_bold_text_with_bright_colors = false
#custom_cursor_colors = true

[general]
import = [
    "~/.config/alacritty/themes/themes/hardhacker.toml"
]
live_config_reload = true

[window]
option_as_alt = "Both" # fixing Alt for MacOS
dynamic_padding = true
decorations = "None"
startup_mode = "Maximized"
opacity = 0.95
blur = true

[window.dimensions]
columns = 100
lines = 85

[window.padding]
x = 10
y = 5

[scrolling]
history = 0
multiplier = 3

[font]
size = 12
# use_thin_strokes = true
# on mac - https://petar.dev/notes/crisp-fonts-alacritty/

[font.normal]
family = "RecMonoLinear Nerd Font Mono"
style = "Regular"

[font.bold]
family = "RecMonoLinear Nerd Font Mono"
style = "Bold"

[font.italic]
family = "RecMonoLinear Nerd Font Mono"
style = "Regular Italic"

[font.offset]
x = 0
y = 3

[font.glyph_offset]
x = 0
y = 0

[colors.cursor]
text = 'CellBackground'
cursor = '#c7ccd1'

[bell]
animation = "EaseOutExpo"
color = "0xffffff"
duration = 0

[mouse]
hide_when_typing = false

[cursor]
style = "Block"
unfocused_hollow = true

[keyboard]
bindings = [
  { key = "A", mods = "Command", chars = "\u0001" },
  { key = "C", mods = "Command", chars = "\u0003" },
  { key = "D", mods = "Command", chars = "\u0004" },
  { key = "E", mods = "Command", chars = "\u0005" },
  # to make Command-H work in MacOS one need to go to
  # Settings > keyboard > Hotkeys > Apps' hotkeys
  # and create some other hotkey for Alacritty's
  # "Hide alacritty"
  { key = "H", mods = "Command", chars = "\u0008" },
  { key = "I", mods = "Command", chars = "\u0009" },
  { key = "J", mods = "Command", chars = "\u000a" },
  { key = "K", mods = "Command", chars = "\u000b" },
  { key = "L", mods = "Command", chars = "\u000c" },
  { key = "O", mods = "Command", chars = "\u000f" },
  { key = "R", mods = "Command", chars = "\u0012" },
  { key = "T", mods = "Command", chars = "\u0014" },
  { key = "U", mods = "Command", chars = "\u0015" },
  { key = "W", mods = "Command", chars = "\u0017" },
  { key = "X", mods = "Command", chars = "\u0018" },
  { key = "Y", mods = "Command", chars = "\u0019" },
  { key = "Z", mods = "Command", chars = "\u001a" },

  # Ctrl-LeftArrow escape sequence, ^[[1;5D
  # \u001b: ESCAPE character
  # \u005b: LEFT SQUARE BRACKET [
  # \u0031: DIGIT ONE 1
  # \u003b: SEMICOLON ;
  # \u0035: DIGIT FIVE 5
  # \u0044: LATIN CAPITAL LETTER D
  { key = "ArrowLeft", mods = "Command", chars = "\u001b\u005b\u0031\u003b\u0035\u0044" },

  # Ctrl-RightArrow escape sequence, ^[[1;5D
  # ^[[1;5C   27 0033 0x1b
  #  91 0133 0x5b
  #  49 0061 0x31
  #  59 0073 0x3b
  #  53 0065 0x35
  #  67 0103 0x43
  { key = "ArrowRight", mods = "Command", chars = "\u001b\u005b\u0031\u003b\u0035\u0043" },
  { key = "ArrowDown", mods = "Command", chars = "\u001b\u005b\u0031\u003b\u0035\u0042" },
  { key = "F", mods = "Control", action = "ToggleMaximized" },
]
