if type brew &>/dev/null
then
  FPATH="$(brew --prefix)/share/zsh/site-functions:${FPATH}"

  autoload -Uz compinit
  compinit
fi

setopt appendhistory # Append history to the history file (no overwriting)
setopt incappendhistory # Immediately append to the history file, not just when a term is killed
setopt histignoredups

source ~/.dotfiles/git/git-prompt.sh
setopt PROMPT_SUBST ; PS1='%n@%m %c$(__git_ps1 " [%s]")\$ '
source ~/.zshrc_local
